const data = {
  products: [
    {
      _id: '1',
      name: 'Dried Flowers and Pampas Bouquet',
      slug: 'Dried-Pampas-Bouquet',
      category: 'Bouquet',
      image: '/images/Bouquet1.jpg',
      price: 50,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Dried Pampas Grass, Palm and Dried Flowers Bouquet',
    },
    {
      _id: '2',
      name: 'Bohemian Handmade Macrame Shelf',
      slug: 'Macrame-Shelf',
      category: 'Shelves',
      image: '/images/Shelf1.jpg',
      price: 70,
      countInStock: 0,
      rating: 4.5,
      numReviews: 14,
      description: 'Bohemian Handmade Macrame Shelf',
    },
    {
      _id: '3',
      name: 'Minimalist wooden Plant pot',
      slug: 'wooden-plant-pot',
      category: 'Plant pot',
      image: '/images/pot1.jpg',
      price: 90,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'Minimalist and geometric wooden Plant pot',
    },
  ],
};
export default data;
